sudo: false
cache:
  directories:
    $HOME/.npm
    $HOME/.cache

language: node_js
node_js:
  - "4"
  - "5"
  - node

os:
  - linux

before_install:
  - npm config set progress false
  - npm i -g npm@3

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional

script: npm test
